<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GeneralsettingResource\Pages;
use App\Filament\Resources\GeneralsettingResource\RelationManagers;
use App\Models\Generalsetting;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class GeneralsettingResource extends Resource
{
    protected static ?string $model = Generalsetting::class;

    protected static ?string $navigationIcon = 'heroicon-o-cog-6-tooth';

    protected static ?string $navigationGroup = 'General Settings';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('logo')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('favicon')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('title')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('colors')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('loader')
                    ->required()
                    ->maxLength(191),
                Forms\Components\TextInput::make('admin_loader')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\Toggle::make('is_talkto')
                    ->required(),
                Forms\Components\Textarea::make('talkto')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('is_language')
                    ->required(),
                Forms\Components\Toggle::make('is_loader')
                    ->required(),
                Forms\Components\Toggle::make('is_disqus')
                    ->required(),
                Forms\Components\Textarea::make('disqus')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('guest_checkout')
                    ->required(),
                Forms\Components\Toggle::make('currency_format')
                    ->required(),
                Forms\Components\TextInput::make('withdraw_fee')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('withdraw_charge')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('shipping_cost')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('mail_driver')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('mail_host')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('mail_port')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('mail_encryption')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('mail_user')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('mail_pass')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('from_email')
                    ->email()
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('from_name')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\Toggle::make('is_smtp')
                    ->required(),
                Forms\Components\Toggle::make('is_comment')
                    ->required(),
                Forms\Components\Toggle::make('is_currency')
                    ->required(),
                Forms\Components\Toggle::make('is_affilate')
                    ->required(),
                Forms\Components\TextInput::make('affilate_charge')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Textarea::make('affilate_banner')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('fixed_commission')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('referral_bonus_referrer')
                    ->required()
                    ->numeric()
                    ->default(500.00),
                Forms\Components\TextInput::make('referral_bonus_referred')
                    ->required()
                    ->numeric()
                    ->default(250.00),
                Forms\Components\Toggle::make('referral_system_active')
                    ->required(),
                Forms\Components\TextInput::make('percentage_commission')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('multiple_shipping')
                    ->required(),
                Forms\Components\TextInput::make('multiple_packaging')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('vendor_ship_info')
                    ->required(),
                Forms\Components\Toggle::make('reg_vendor')
                    ->required(),
                Forms\Components\TextInput::make('footer_color')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('copyright_color')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('copyright')
                    ->maxLength(255)
                    ->default(null),
                Forms\Components\Toggle::make('is_admin_loader')
                    ->required(),
                Forms\Components\Toggle::make('is_verification_email')
                    ->required(),
                Forms\Components\TextInput::make('wholesell')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('is_capcha')
                    ->required(),
                Forms\Components\TextInput::make('capcha_secret_key')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('capcha_site_key')
                    ->maxLength(100)
                    ->default(null),
                Forms\Components\TextInput::make('error_banner_404')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\TextInput::make('error_banner_500')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\Toggle::make('is_popup')
                    ->required(),
                Forms\Components\Textarea::make('popup_background')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('breadcrumb_banner')
                    ->maxLength(500)
                    ->default(null),
                Forms\Components\TextInput::make('invoice_logo')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\FileUpload::make('user_image')
                    ->image(),
                Forms\Components\TextInput::make('vendor_color')
                    ->maxLength(191)
                    ->default(null),
                Forms\Components\Toggle::make('is_secure')
                    ->required(),
                Forms\Components\Toggle::make('is_report')
                    ->required(),
                Forms\Components\Textarea::make('footer_logo')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('show_stock')
                    ->required(),
                Forms\Components\Toggle::make('is_maintain')
                    ->required(),
                Forms\Components\TextInput::make('header_color')
                    ->required(),
                Forms\Components\Textarea::make('maintain_text')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('is_buy_now')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('version')
                    ->maxLength(40)
                    ->default(null),
                Forms\Components\Toggle::make('affilate_product')
                    ->required(),
                Forms\Components\Toggle::make('verify_product')
                    ->required(),
                Forms\Components\TextInput::make('page_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('flash_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('hot_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('new_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('sale_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('best_seller_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('popular_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('top_rated_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('big_save_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('trending_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('seller_product_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('wishlist_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('vendor_page_count')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('min_price')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('max_price')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Toggle::make('post_count')
                    ->required(),
                Forms\Components\Textarea::make('product_page')
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('wishlist_page')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('is_contact_seller')
                    ->required(),
                Forms\Components\Toggle::make('is_debug')
                    ->required(),
                Forms\Components\TextInput::make('decimal_separator')
                    ->maxLength(10)
                    ->default(null),
                Forms\Components\TextInput::make('thousand_separator')
                    ->maxLength(10)
                    ->default(null),
                Forms\Components\Toggle::make('is_cookie')
                    ->required(),
                Forms\Components\Toggle::make('product_affilate')
                    ->required(),
                Forms\Components\TextInput::make('product_affilate_bonus')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('is_reward')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('reward_point')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('reward_dolar')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('physical')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('digital')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('license')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('listing')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('affilite')
                    ->required()
                    ->numeric()
                    ->default(1),
                Forms\Components\TextInput::make('partner_title')
                    ->maxLength(250)
                    ->default(null),
                Forms\Components\Textarea::make('partner_text')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('deal_title')
                    ->maxLength(255)
                    ->default(null),
                Forms\Components\TextInput::make('deal_details')
                    ->maxLength(600)
                    ->default(null),
                Forms\Components\DatePicker::make('deal_time'),
                Forms\Components\TextInput::make('deal_background')
                    ->maxLength(500)
                    ->default(null),
                Forms\Components\TextInput::make('delivery_base_fee')
                    ->required()
                    ->numeric()
                    ->default(1000.0000),
                Forms\Components\TextInput::make('delivery_stopover_fee')
                    ->required()
                    ->numeric()
                    ->default(300.0000),
                Forms\Components\TextInput::make('rider_percentage_commission')
                    ->required()
                    ->numeric()
                    ->default(80.0000),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('logo')
                    ->searchable(),
                Tables\Columns\TextColumn::make('favicon')
                    ->searchable(),
                Tables\Columns\TextColumn::make('title')
                    ->searchable(),
                Tables\Columns\TextColumn::make('colors')
                    ->searchable(),
                Tables\Columns\TextColumn::make('loader')
                    ->searchable(),
                Tables\Columns\TextColumn::make('admin_loader')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_talkto')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_language')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_loader')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_disqus')
                    ->boolean(),
                Tables\Columns\IconColumn::make('guest_checkout')
                    ->boolean(),
                Tables\Columns\IconColumn::make('currency_format')
                    ->boolean(),
                Tables\Columns\TextColumn::make('withdraw_fee')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('withdraw_charge')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('shipping_cost')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mail_driver')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mail_host')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mail_port')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mail_encryption')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mail_user')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mail_pass')
                    ->searchable(),
                Tables\Columns\TextColumn::make('from_email')
                    ->searchable(),
                Tables\Columns\TextColumn::make('from_name')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_smtp')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_comment')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_currency')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_affilate')
                    ->boolean(),
                Tables\Columns\TextColumn::make('affilate_charge')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('fixed_commission')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('referral_bonus_referrer')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('referral_bonus_referred')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('referral_system_active')
                    ->boolean(),
                Tables\Columns\TextColumn::make('percentage_commission')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('multiple_shipping')
                    ->boolean(),
                Tables\Columns\TextColumn::make('multiple_packaging')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('vendor_ship_info')
                    ->boolean(),
                Tables\Columns\IconColumn::make('reg_vendor')
                    ->boolean(),
                Tables\Columns\TextColumn::make('footer_color')
                    ->searchable(),
                Tables\Columns\TextColumn::make('copyright_color')
                    ->searchable(),
                Tables\Columns\TextColumn::make('copyright')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_admin_loader')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_verification_email')
                    ->boolean(),
                Tables\Columns\TextColumn::make('wholesell')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_capcha')
                    ->boolean(),
                Tables\Columns\TextColumn::make('capcha_secret_key')
                    ->searchable(),
                Tables\Columns\TextColumn::make('capcha_site_key')
                    ->searchable(),
                Tables\Columns\TextColumn::make('error_banner_404')
                    ->searchable(),
                Tables\Columns\TextColumn::make('error_banner_500')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_popup')
                    ->boolean(),
                Tables\Columns\TextColumn::make('breadcrumb_banner')
                    ->searchable(),
                Tables\Columns\TextColumn::make('invoice_logo')
                    ->searchable(),
                Tables\Columns\ImageColumn::make('user_image'),
                Tables\Columns\TextColumn::make('vendor_color')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_secure')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_report')
                    ->boolean(),
                Tables\Columns\IconColumn::make('show_stock')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_maintain')
                    ->boolean(),
                Tables\Columns\TextColumn::make('header_color'),
                Tables\Columns\TextColumn::make('is_buy_now')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('version')
                    ->searchable(),
                Tables\Columns\IconColumn::make('affilate_product')
                    ->boolean(),
                Tables\Columns\IconColumn::make('verify_product')
                    ->boolean(),
                Tables\Columns\TextColumn::make('page_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('flash_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('hot_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('new_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('sale_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('best_seller_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('popular_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('top_rated_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('big_save_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('trending_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('seller_product_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('wishlist_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('vendor_page_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('min_price')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('max_price')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('post_count')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_contact_seller')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_debug')
                    ->boolean(),
                Tables\Columns\TextColumn::make('decimal_separator')
                    ->searchable(),
                Tables\Columns\TextColumn::make('thousand_separator')
                    ->searchable(),
                Tables\Columns\IconColumn::make('is_cookie')
                    ->boolean(),
                Tables\Columns\IconColumn::make('product_affilate')
                    ->boolean(),
                Tables\Columns\TextColumn::make('product_affilate_bonus')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('is_reward')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('reward_point')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('reward_dolar')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('physical')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('digital')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('license')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('listing')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('affilite')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('partner_title')
                    ->searchable(),
                Tables\Columns\TextColumn::make('deal_title')
                    ->searchable(),
                Tables\Columns\TextColumn::make('deal_details')
                    ->searchable(),
                Tables\Columns\TextColumn::make('deal_time')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deal_background')
                    ->searchable(),
                Tables\Columns\TextColumn::make('delivery_base_fee')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('delivery_stopover_fee')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('rider_percentage_commission')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGeneralsettings::route('/'),
            'create' => Pages\CreateGeneralsetting::route('/create'),
            'edit' => Pages\EditGeneralsetting::route('/{record}/edit'),
        ];
    }
}
